# Generated by Django 3.2.12 on 2022-03-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220310_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapcity',
            name='idDepartment',
            field=models.ForeignKey(db_column='idDepartment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.scrapdepartment'),
        ),
        migrations.AlterField(
            model_name='scrapdepartment',
            name='idregion',
            field=models.ForeignKey(db_column='idregion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.scrapdata'),
        ),
        migrations.AlterField(
            model_name='scrapquarters',
            name='idCity',
            field=models.ForeignKey(db_column='idCity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.scrapcity'),
        ),
        migrations.AlterField(
            model_name='scrapstreets',
            name='idQuarter',
            field=models.ForeignKey(db_column='idQuarter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.scrapquarters'),
        ),
    ]
